// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCmvP1ZgQFQWP5yYJiNJEQZkmeig0fEzo',
    appId: '1:998787427223:web:af38ebb2a62cecd2d2f2d2',
    messagingSenderId: '998787427223',
    projectId: 'flutter-snake-game-e226c',
    authDomain: 'flutter-snake-game-e226c.firebaseapp.com',
    storageBucket: 'flutter-snake-game-e226c.appspot.com',
    measurementId: 'G-H8CBLZ56ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCULluIbT0KW_hVpFSnqYvKxDsBBdeUyKs',
    appId: '1:998787427223:android:f0b85f0de0e5c845d2f2d2',
    messagingSenderId: '998787427223',
    projectId: 'flutter-snake-game-e226c',
    storageBucket: 'flutter-snake-game-e226c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO0ee-2BNz5971dIwpw6OWG-JWb0TdPCc',
    appId: '1:998787427223:ios:36afe94dfa074290d2f2d2',
    messagingSenderId: '998787427223',
    projectId: 'flutter-snake-game-e226c',
    storageBucket: 'flutter-snake-game-e226c.appspot.com',
    iosBundleId: 'com.example.snakeGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO0ee-2BNz5971dIwpw6OWG-JWb0TdPCc',
    appId: '1:998787427223:ios:a6d0d9c9e08bf5ded2f2d2',
    messagingSenderId: '998787427223',
    projectId: 'flutter-snake-game-e226c',
    storageBucket: 'flutter-snake-game-e226c.appspot.com',
    iosBundleId: 'com.example.snakeGame.RunnerTests',
  );
}
